version: "2"
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - errcheck
    - exhaustruct
    - fatcontext
    - funlen
    - intrange
    - lll
    - noinlineerr
    - nolintlint
    - nonamedreturns
    - perfsprint
    - revive
    - usetesting
    - varnamelen
    - wsl
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
        - experimental
        - opinionated
    varnamelen:
      min-name-length: 2
      ignore-decls:
        - l *zap.Logger
        - l *slog.Logger
        - l slog.Logger
        - w http.ResponseWriter
        - r chi.Router
        - fs *flag.FlagSet
        - r *http.Request
        - eg *errgroup.Group
        - sw *statuswriter.StatusWriter
        - db *bun.DB
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
  exclusions:
    generated: disable
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo
  exclusions:
    generated: disable
  settings:
    golines:
      max-len: 120
      tab-len: 2
      shorten-comments: true
      reformat-tags: true
      chain-split-dots: true
