name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{inputs.version}}"
          prerelease: false
          title: "Release ${{inputs.version}}"
